### PR TITLE
Use Git to update miners

### PR DESCRIPTION
**Pull request by LuKePicci**
Pros vs the old approach:
- users will only have to do "git pull origin master" & "./nvOC_miners_update.sh" to get an updated miners collection (can also be added as a nvOC script subcommand)
- the whole process is very much faster due to fewer file I/O operations performed (which is a good thig at least until we manage to avoid stopping miners for the whole update process duration)
- it's ready for nvOC19-2.1 where miners have been moved to a separate directory but it also works well for old nvOC releases
- it's easier to manage since there is no need to upload a package to cloud drive and then incorporating that link in the miner's installer each time a miner is updated
- a simple "git stash" & installer re-run will revert all user modifications enabling fast recovery

Also a few other minor changes have been made, none of them should break or conflict with existing deployments,

### CODE REVIEW

**Comment by papampi** [comment]
How about instead of full directory, only add executable and version file, then if compile requested, update script fetch from original git repo, download and recompile?

**Comment by LuKePicci** [comment]
Absolutely a nice idea. Can be done,  you only need to add submodules pointing specific git commit for each miner repo. I tried to remain fully compliant to the previous structure but if you intend to go on in this direction it would be better to create for each miner a subfolder called "src" to clone the repo into and create a link to the output binary in the upper directory where also the version file is, instead of adding the version file (and maybe something else) to the same directory of the cloned repo, so it will not be tracked by the submodule repo. I will work on it and update this PR if you like.

**Comment by papampi** [comment]
Amazing idea with src folder, would be nice if you have time to work on it.
Just keep in mind on most of miners we cant use master repo and pull latest as they keep working on them and most of the time release point is much behind latest and may contain bugs.
So I think we should add latest release tar gz for download, recompile and copy the compiled from src folder.

**Comment by LuKePicci** [comment]
It's almost done, all submodules are pointing the specific stable version of the repo which is provided as precompiled binary also. They will not follow latest commits unless we update the submodule pointer here in this repo.

Two things are missing:
- cleanup of the existing tarballs: some still contains useless sources that get extracted in the old place, they have to contain only precompiled binaries
- add also ASccminer, KXccminer and SPccminer as submodules: since they are present in the nvOC image but not here in the repo while the updater script already supports their recompilation

**Comment by papampi** [comment]
Awesome, sent you  ASccminer, KXccminer and SPccminer links to add.

**Comment by papampi** [comment]
Can we do "git pull" on home folder for 19-2.0?
If not lets leave the 19-2.0, and merge this to 19-2.1 branch so we can git pull on /home/m1/miners

**Comment by LuKePicci** [comment]
Technically you could init a git repo in the home folder but then one should be able to manage the local clone of the repo in the correct way to avoid some strange things happen. So yes, I advice leaving this for the 2.1 branch only. If you intend to use this for 2.0 also, the easiest and safest thing that can be done is to run this in the miners subfolder as like as in 2.1 but then create symlinks in the legacy positions to point the binaries in the new location. It may be worthless.

**Pull request merged**
