### PR TITLE
Update bminer, lolMiner, gminer

### PR DESCRIPTION
**Pull request by LuKePicci**
Still missing the pm manifest for lolMiner, I would appreciate if anybody here could kindly build it and test all this updated miners.

### CODE REVIEW

**Comment by delawr0190** [comment]
Looks great.  I can handle the testing of it all.

@papampi Can you get lolminer building?

**Comment by papampi** [comment]
Sure added to 3.1-miners-prep
https://github.com/papampi/nvOC_miners/tree/3.1-miners-prep/LOLMINER/0.6

**Review by papampi — APPROVED** [review]
All looks good, 
Added lolMiner to 3.1-miners-prep so @delawr0190 can test.

**Comment by LuKePicci** [comment]
Now merging, if something doesn't work as expected will fix in its merge after testing.

**Pull request merged**
