### PR TITLE
Support cuda-10 miners

### PR DESCRIPTION
**Pull request by papampi**
Cuda 10 support

### CODE REVIEW

**Review by LuKePicci — APPROVED** [review]
I will not port this patch into 3.1 branch as this relates to old builtin miners. I will in case it for any reason this should become necessary.

**Comment by papampi** [comment]
I'm going to make a new 16.04 dual cuda image, since we are getting more and more issues with tempcontrol on 18.04.
Dont know if all the miners has cuda 10 support yet or not so will go with cuda 8 + 9.2 for now.

**Comment by papampi** [comment]
Also have not tested this yet, so will keep it open to merge after some tests

**Comment by LuKePicci** [comment]
Ok, sounds good.

**Comment by papampi** [comment]
Can be achieved via Miners Manifests.
Closing.

**Pull request closed without merging**
